### ISSUE TITLE
Issue with pip install on macOS

### ISSUE THREAD

**Issue by jorshi** [DBraun/DawDreamer#49]
First off, thanks for your work on this project! This is looking really cool, I've used RenderMan a bunch and this updated package will be very useful :)

I'm having some difficulties with the pip install on Mac OS (11.2). 

Python info:
```
>>> import sys
>>> sys.version
'3.9.7 (default, Sep 16 2021, 08:50:36) \n[Clang 10.0.0 ]'
```

First, pip can't find the pypi package:
```
pip install dawdreamer
ERROR: Could not find a version that satisfies the requirement dawdreamer (from versions: none)
ERROR: No matching distribution found for dawdreamer
```

I believe this is because none of the wheels are supported on my machine? I tried downloading the wheels and installing using:
```
pip install dawdreamer-0.5.7.5-cp39-cp39-macosx_11_0_x86_64.whl
ERROR: dawdreamer-0.5.7.5-cp39-cp39-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
```

So then I tried cloning the repo and doing a local pip install:
```
git clone https://github.com/DBraun/DawDreamer.git
pip install -e ./DawDreamer

Obtaining file:///Users/jshier/development/Libraries/DawDreamer
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/jshier/opt/anaconda3/bin/python /Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/tmpexe4_ww7
       cwd: /Users/jshier/development/Libraries/DawDreamer
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/pip-build-env-bqchioto/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/pip-build-env-bqchioto/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/pip-build-env-bqchioto/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 16, in <module>
      python_requires = "==" + os.environ['PYTHONMAJOR'] + '.*'  # set with github action
    File "/Users/jshier/opt/anaconda3/lib/python3.8/os.py", line 675, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PYTHONMAJOR'
  ----------------------------------------
WARNING: Discarding file:///Users/jshier/development/Libraries/DawDreamer. Command errored out with exit status 1: /Users/jshier/opt/anaconda3/bin/python /Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/tmpexe4_ww7 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /Users/jshier/opt/anaconda3/bin/python /Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/tmpexe4_ww7 Check the logs for full command output.
```

I saw that you set PYTHONMAJOR as an environment variable in the Github workflows:
```
export PYTHONMAJOR=3.9
pip install -e ./DawDreamer

Obtaining file:///Users/jshier/development/Libraries/DawDreamer
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/jshier/opt/anaconda3/bin/python /Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/tmpsr7snsa7
       cwd: /Users/jshier/development/Libraries/DawDreamer
  Complete output (21 lines):
  python_requires: ==3.9.*
  Traceback (most recent call last):
    File "/Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/pip-build-env-3icdffle/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/pip-build-env-3icdffle/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/pip-build-env-3icdffle/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 69, in <module>
      shutil.copy(os.path.join(build_folder, 'dawdreamer.so'), os.path.join('dawdreamer', 'dawdreamer.so'))
    File "/Users/jshier/opt/anaconda3/lib/python3.8/shutil.py", line 415, in copy
      copyfile(src, dst, follow_symlinks=follow_symlinks)
    File "/Users/jshier/opt/anaconda3/lib/python3.8/shutil.py", line 261, in copyfile
      with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  FileNotFoundError: [Errno 2] No such file or directory: '/Users/jshier/development/Libraries/DawDreamer/Builds/MacOSX/build/Release/dawdreamer.so'
  ----------------------------------------
WARNING: Discarding file:///Users/jshier/development/Libraries/DawDreamer. Command errored out with exit status 1: /Users/jshier/opt/anaconda3/bin/python /Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/tmpsr7snsa7 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /Users/jshier/opt/anaconda3/bin/python /Users/jshier/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/d3/8t_hqbqd77n1n8y47rwyb2nm0000gn/T/tmpsr7snsa7 Check the logs for full command output.
```

Thanks for your help!

**Comment by DBraun** [comment]
Hi, thanks for trying this out and your very good debug efforts. Sorry for the trouble it has already caused. This is my first complex project on pypi so it is going through some growing pains despite my efforts to test with github actions etc...

First, are you using an M1 mac? If so, you might need to use the `dawdreamer-0.5.7.5-cp39-cp39-macosx_11_0_universal2.whl`. I've tested building locally and pip installing on an Intel mac running 11.3, but I haven't done the same for M1.

Second, some more instructions for building locally are here https://github.com/DBraun/DawDreamer/wiki/Developer's-Guide and I updated the `Building wheel` section just now.

You will have to use those instructions to build the dawdreamer.so before building the wheel.

I see that you're using Anaconda. That may not work at the moment, but I'll test it next week.

Thanks for your patience on this. I want to get it working for you so please hang in there and let me know what bumps happen next... Due to some business I will have to aim for testing Anaconda more thoroughly next week though.

**Comment by jorshi** [comment]
Thanks for your response! I am not on an M1 mac, I tried both the mac wheels for python 3.9. Also tried outside of my anaconda env, and that was no luck either.

I've successfully built dawdreamer using the manual build instructions in the past, so I can stick to that for now. Excited to see that a pypi package is in the works though, that will be an excellent addition to this project - happy to help test where I can.

**Comment by DBraun** [comment]
It's a bummer that `pip install dawdreamer` isn't just working. I searched some things and people say to upgrade pip: `pip install --upgrade pip`

I want to rule out the mismatch between python 3.9 and your Anaconda env which might be 3.8.

Could you do `pip --version` and `python --version`?

When you can, please upload the error messages for
`pip install dawdreamer-0.5.7.5-cp38-cp38-macosx_11_0_x86_64.whl` with pip related to Python 3.8

or `pip install dawdreamer-0.5.7.5-cp39-cp39-macosx_11_0_x86_64.whl` with pip related to Python 3.9

**Comment by jorshi** [comment]
Okay, some progress: I was able to install dawdreamer using pip with python3.8 (no anaconda), and then directly from the wheels with both python3.8 and python3.9. Unfortunately the faust stuff doesn't seem to be working though.

To rule out the potential anaconda issue I am running these commands from outside any env. These are python versions installed with homebrew:

```
jshier@Jordies-MBP ~ % python3.8 --version
Python 3.8.12

jshier@Jordies-MBP ~ % python3.8 -m pip --version
pip 21.2.4 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)

jshier@Jordies-MBP ~ % python3.9 --version
Python 3.9.7

jshier@Jordies-MBP ~ % python3.9 -m pip --version
pip 21.2.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
```

Tested some various installations:

### Python 3.8

Testing from pypi:
```
python3.8 -m pip install dawdreamer --no-cache
Collecting dawdreamer
  Downloading dawdreamer-0.5.7.5-cp38-cp38-macosx_11_0_x86_64.whl (21.5 MB)
     |████████████████████████████████| 21.5 MB 6.2 MB/s
Installing collected packages: dawdreamer
Successfully installed dawdreamer-0.5.7.5

python3.8 -m pytest .
========================================================== test session starts ===========================================================
platform darwin -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/jshier/development/Libraries/DawDreamer
collected 19 items

test_faust_dx7.py F                                                                                                                [  5%]
test_faust_poly.py F                                                                                                               [ 10%]
test_faust_poly_sampler.py F                                                                                                       [ 15%]
test_faust_poly_wavetable.py FF                                                                                                    [ 26%]
test_faust_processor.py FFFF                                                                                                       [ 47%]
test_impulse.py ..                                                                                                                 [ 57%]
test_playback_processor.py .                                                                                                       [ 63%]
test_playbackwarp_processor.py ..                                                                                                  [ 73%]
test_plugins.py ...                                                                                                                [ 89%]
test_record.py .                                                                                                                   [ 94%]
test_sampler.py .                                                                                                                  [100%]
```

Testing with wheels:
```
python3.8 -m pip install dawdreamer-0.5.7.5-cp38-cp38-macosx_11_0_x86_64.whl
Successfully installed dawdreamer-0.5.7.5

jshier@Jordies-MBP tests % python3.8 -m pytest .
========================================================== test session starts ===========================================================
platform darwin -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/jshier/development/Libraries/DawDreamer
collected 19 items

test_faust_dx7.py F                                                                                                                [  5%]
test_faust_poly.py F                                                                                                               [ 10%]
test_faust_poly_sampler.py F                                                                                                       [ 15%]
test_faust_poly_wavetable.py FF                                                                                                    [ 26%]
test_faust_processor.py FFFF                                                                                                       [ 47%]
test_impulse.py ..                                                                                                                 [ 57%]
test_playback_processor.py .                                                                                                       [ 63%]
test_playbackwarp_processor.py ..                                                                                                  [ 73%]
test_plugins.py ...                                                                                                                [ 89%]
test_record.py .                                                                                                                   [ 94%]
test_sampler.py .                                                                                                                  [100%]
```

```
python3.8 -m pip install dawdreamer-0.5.7.5-cp38-cp38-macosx_11_0_universal2.whl
Successfully installed dawdreamer-0.5.7.5

========================================================== test session starts ===========================================================
platform darwin -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/jshier/development/Libraries/DawDreamer
collected 19 items

test_faust_dx7.py F                                                                                                                [  5%]
test_faust_poly.py F                                                                                                               [ 10%]
test_faust_poly_sampler.py F                                                                                                       [ 15%]
test_faust_poly_wavetable.py FF                                                                                                    [ 26%]
test_faust_processor.py FFFF                                                                                                       [ 47%]
test_impulse.py ..                                                                                                                 [ 57%]
test_playback_processor.py .                                                                                                       [ 63%]
test_playbackwarp_processor.py ..                                                                                                  [ 73%]
test_plugins.py ...                                                                                                                [ 89%]
test_record.py .                                                                                                                   [ 94%]
test_sampler.py .                                                                                                                  [100%]
```

### Python 3.9

```
python3.9 -m pip install dawdreamer --no-cache
ERROR: Could not find a version that satisfies the requirement dawdreamer (from versions: none)
ERROR: No matching distribution found for dawdreamer
```

Installing the wheels directly:
```
python3.9 -m pip install dawdreamer-0.5.7.5-cp39-cp39-macosx_11_0_x86_64.whl
Successfully installed dawdreamer-0.5.7.5

test_faust_dx7.py F                                                                                                                [  5%]
test_faust_poly.py F                                                                                                               [ 10%]
test_faust_poly_sampler.py F                                                                                                       [ 15%]
test_faust_poly_wavetable.py FF                                                                                                    [ 26%]
test_faust_processor.py FFFF                                                                                                       [ 47%]
test_impulse.py ..                                                                                                                 [ 57%]
test_playback_processor.py .                                                                                                       [ 63%]
test_playbackwarp_processor.py ..                                                                                                  [ 73%]
test_plugins.py ...                                                                                                                [ 89%]
test_record.py .                                                                                                                   [ 94%]
test_sampler.py .                                                                                                                  [100%]
```

```
python3.9 -m pip install dawdreamer-0.5.7.5-cp39-cp39-macosx_11_0_universal2.whl
Successfully installed dawdreamer-0.5.7.5

test_faust_dx7.py F                                                                                                                [  5%]
test_faust_poly.py F                                                                                                               [ 10%]
test_faust_poly_sampler.py F                                                                                                       [ 15%]
test_faust_poly_wavetable.py FF                                                                                                    [ 26%]
test_faust_processor.py FFFF                                                                                                       [ 47%]
test_impulse.py ..                                                                                                                 [ 57%]
test_playback_processor.py .                                                                                                       [ 63%]
test_playbackwarp_processor.py ..                                                                                                  [ 73%]
test_plugins.py ...                                                                                                                [ 89%]
test_record.py .                                                                                                                   [ 94%]
test_sampler.py .                                                                                                                  [100%]
```

**Comment by DBraun** [comment]
For simplicity let's just focus on 3.8 for now. I fixed a path-related Faust issue for macOS and pushed to pypi (0.5.7.7). Could you try the latest wheel for Python 3.8 and do the verbose output for 3.8?

`python3.8 -m pytest -s .`

**Comment by shakfu** [comment]
May I suggest you set the required version to 3.8 until the 3.9 issues are fixed.

**Comment by DBraun** [comment]
@shakfu I’m not sure. Continuing to put the 3.9 wheel on PyPi seems like a good way to help people test it one way or another. It seems to be compiling correctly.

**Comment by DBraun** [comment]
Thanks all for trying. I'm now pretty sure the issue is that `thirdparty/libfaust/darwin-x64/Release/libfaust.a` was built for macOS 11.0 or higher. So all of the macOS tests have been working because they were on 11 but 10.15 is in fact not yet supported. I will have to automate the building of libfaust in the TD-Faust repo and get back to this. Thanks for your patience.

**Comment by DBraun** [comment]
Hi everyone, I've worked a lot on making sure that the wheels on PyPI actually work for both intel-based macs and M1. I've also cleaned up the other version issues related to other libraries such as libfaust. For some reason `pip install dawdreamer` still isn't working well but please give the wheels a new try: https://pypi.org/project/dawdreamer/#files

**Comment by shakfu** [comment]
This is really great stuff. I'm not sure why you said `pip install dawdreamer` doesn't work. It just worked perfectly for me (macOS Catalina on x86_64):

```bash
$ virtualenv venv && source venv/bin/activate
...
(venv) vole:Downloads sa$ pip install dawdreamer
Collecting dawdreamer
  Downloading dawdreamer-0.5.8.2-cp39-cp39-macosx_10_15_universal2.whl (36.4 MB)
     |████████████████████████████████| 36.4 MB 17.1 MB/s
Installing collected packages: dawdreamer
Successfully installed dawdreamer-0.5.8.2
(venv) $ python
Python 3.9.9 (main, Nov 21 2021, 03:22:47)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dawdreamer as daw
>>> engine = daw.RenderEngine(44100, 512)
>>> exit()
```

**Comment by DBraun** [comment]
Closing. I think pip is working fine on macOS. I just tested 0.6.0 directly from pypi.
